const c = @import("./c.zig");

pub const FDBError = error {
  OperationFailed,
  TimedOut,
  TransactionTooOld,
  FutureVersion,
  NotCommitted,
  CommitUnknownResult,
  TransactionCancelled,
  TransactionTimedOut,
  TooManyWatches,
  WatchesDisabled,
  AccessedUnreadable,
  ProcessBehind,
  DatabaseLocked,
  ClusterVersionChanged,
  ExternalClientAlreadyLoaded,
  ProxyMemoryLimitExceeded,
  OperationCancelled,
  FutureReleased,
  PlatformError,
  LargeAllocFailed,
  PerformanceCounterError,
  IoError,
  FileNotFound,
  BindFailed,
  FileNotReadable,
  FileNotWritable,
  NoClusterFileFound,
  FileTooLarge,
  ClientInvalidOperation,
  CommitReadIncomplete,
  TestSpecificationInvalid,
  KeyOutsideLegalRange,
  InvertedRange,
  InvalidOptionValue,
  InvalidOption,
  NetworkNotSetup,
  NetworkAlreadySetup,
  ReadVersionAlreadySet,
  VersionInvalid,
  RangeLimitsInvalid,
  InvalidDatabaseName,
  AttributeNotFound,
  FutureNotSet,
  FutureNotError,
  UsedDuringCommit,
  InvalidMutationType,
  TransactionInvalidVersion,
  NoCommitVersion,
  EnvironmentVariableNetworkOptionFailed,
  TransactionReadOnly,
  IncompatibleProtocolVersion,
  TransactionTooLarge,
  KeyTooLarge,
  ValueTooLarge,
  ConnectionStringInvalid,
  AddressInUse,
  InvalidLocalAddress,
  TLSError,
  UnsupportedOperation,
  ApiVersionUnset,
  ApiVersionAlreadySet,
  ApiVersionInvalid,
  ApiVersionNotSupported,
  ExactModeWithoutLimits,
  UnknownError,
  InternalError
};

pub fn handleError(rc: c.fdb_error_t) FDBError!void {
  if (rc > 0) {
    return codeToError(rc);
  }
}

fn codeToError(err_code: c.fdb_error_t) FDBError {
  return switch(err_code) {
    1000 => FDBError.OperationFailed,
    1004 => FDBError.TimedOut,
    1007 => FDBError.TransactionTooOld,
    1009 => FDBError.FutureVersion,
    1020 => FDBError.NotCommitted,
    1021 => FDBError.CommitUnknownResult,
    1025 => FDBError.TransactionCancelled,
    1031 => FDBError.TransactionTimedOut,
    1032 => FDBError.TooManyWatches,
    1034 => FDBError.WatchesDisabled,
    1036 => FDBError.AccessedUnreadable,
    1037 => FDBError.ProcessBehind,
    1038 => FDBError.DatabaseLocked,
    1039 => FDBError.ClusterVersionChanged,
    1040 => FDBError.ExternalClientAlreadyLoaded,
    1042 => FDBError.ProxyMemoryLimitExceeded,
    1101 => FDBError.OperationCancelled,
    1102 => FDBError.FutureReleased,
    1500 => FDBError.PlatformError,
    1501 => FDBError.LargeAllocFailed,
    1502 => FDBError.PerformanceCounterError,
    1510 => FDBError.IoError,
    1511 => FDBError.FileNotFound,
    1512 => FDBError.BindFailed,
    1513 => FDBError.FileNotReadable,
    1514 => FDBError.FileNotWritable,
    1515 => FDBError.NoClusterFileFound,
    1516 => FDBError.FileTooLarge,
    2000 => FDBError.ClientInvalidOperation,
    2002 => FDBError.CommitReadIncomplete,
    2003 => FDBError.TestSpecificationInvalid,
    2004 => FDBError.KeyOutsideLegalRange,
    2005 => FDBError.InvertedRange,
    2006 => FDBError.InvalidOptionValue,
    2007 => FDBError.InvalidOption,
    2008 => FDBError.NetworkNotSetup,
    2009 => FDBError.NetworkAlreadySetup,
    2010 => FDBError.ReadVersionAlreadySet,
    2011 => FDBError.VersionInvalid,
    2012 => FDBError.RangeLimitsInvalid,
    2013 => FDBError.InvalidDatabaseName,
    2014 => FDBError.AttributeNotFound,
    2015 => FDBError.FutureNotSet,
    2016 => FDBError.FutureNotError,
    2017 => FDBError.UsedDuringCommit,
    2018 => FDBError.InvalidMutationType,
    2020 => FDBError.TransactionInvalidVersion,
    2021 => FDBError.NoCommitVersion,
    2022 => FDBError.EnvironmentVariableNetworkOptionFailed,
    2023 => FDBError.TransactionReadOnly,
    2100 => FDBError.IncompatibleProtocolVersion,
    2101 => FDBError.TransactionTooLarge,
    2102 => FDBError.KeyTooLarge,
    2103 => FDBError.ValueTooLarge,
    2104 => FDBError.ConnectionStringInvalid,
    2105 => FDBError.AddressInUse,
    2106 => FDBError.InvalidLocalAddress,
    2107 => FDBError.TLSError,
    2108 => FDBError.UnsupportedOperation,
    2200 => FDBError.ApiVersionUnset,
    2201 => FDBError.ApiVersionAlreadySet,
    2202 => FDBError.ApiVersionInvalid,
    2203 => FDBError.ApiVersionNotSupported,
    2210 => FDBError.ExactModeWithoutLimits,
    4000 => FDBError.UnknownError,
    4100 => FDBError.InternalError,
    else => unreachable
  };
}